set_property SRC_FILE_INFO {cfile:C:/Users/Administrator1/Vivado/4bitcounter/counter/counter.srcs/constrs_1/new/constraints.xdc rfile:../../../counter.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports CLR]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports C]
